Update patch set 1
Patch Set 1:

=== Finished presubmit run: L66300000081331207 ===

FAIL: Some checks failed. See below.


=== aosp-master/aosp_arm64-eng ===

PASS: Built aosp-master/aosp_arm64-eng/4171426 (ToT). See https://android-build.googleplex.com/builds/pending/P4541361/aosp_arm64-eng/latest


=== aosp-master/aosp_x86-eng ===

PASS: Built aosp-master/aosp_x86-eng/4171335 (ToT). See https://android-build.googleplex.com/builds/pending/P4541362/aosp_x86-eng/latest


=== git_master/bullhead-userdebug_fastbuild3a_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4171391 (could not apply 7b7ac1c... Docs: Changes to source.android.com). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4541358/bullhead-userdebug_fastbuild3a_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq

SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4171391 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux


=== git_master/gce_x86_phone-userdebug_fastbuild3c_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4171391 (could not apply 7b7ac1c... Docs: Changes to source.android.com). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4541359/gce_x86_phone-userdebug_fastbuild3c_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq

CONFLICT: Your changes failed to cherry-pick against build 4171391 (\'ETIMEDOUT\' was not declared in this scope".). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4541364/test_suites_x86_64_fastbuild3d_linux/latest

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4171391 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4171391 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4171391 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux


=== git_master/sailfish-userdebug_fastbuild3_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4171242 (could not apply 7b7ac1c... Docs: Changes to source.android.com). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4541363/sailfish-userdebug_fastbuild3_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq. 
Note: This is a checkbuild (go/checkbuild). It will take longer and could uncover errors not found in other builds.

CONFLICT: Your changes failed to cherry-pick against build 4171391 (could not apply 7b7ac1c... Docs: Changes to source.android.com). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4541360/sailfish-userdebug_fastbuild3_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq. 
Note: This is a checkbuild (go/checkbuild). It will take longer and could uncover errors not found in other builds.

WARNING: The tip-of-tree(4171391) for git_master/sailfish-userdebug_fastbuild3_linux may be broken.
Presubmit builds based on the tip-of-tree (4171391) and the
last-known-good-build(4171242) also fail. This could be due to the
pre-existing error, a new error in this change, or both.



===

Have a question? Found a bug? http://go/treehugger-troubleshoot

Patch-set: 1
Tag: autogenerated:TreeHugger:Verify-Fail